# Generated by Django 4.2.7 on 2023-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='intro',
            field=models.TextField(max_length=2500),
        ),
    ]
